### ISSUE TITLE
IndexOutOfBounds triggered by Translator.selectShortestField

### ISSUE THREAD

**Issue by icmccorm** [gradual-verification/silicon-gv#38] opened 2022-05-19 14:52 UTC
When running the following two permutations ([example 1](https://github.com/gradual-verification/silicon-gv/files/8730370/err1.txt), [example 2](https://github.com/gradual-verification/silicon-gv/files/8730372/err2.txt)) of List, an IndexOutOfBoundsException is thrown. The source of the exception is in [Translator](https://github.com/gradual-verification/silicon-gv/blob/master/src/main/scala/supporters/Translator.scala). It occurs on line 169 when an empty `candidateFields` is indexed into:
```
    } else {
      // in this case, we only have a list of receivers, so we select one
      // (they should all be equal in length!)
      Some(candidateFields(0))
    }
```
Returning `None` if the list is empty triggers an additional exception on lines 575-578 of [Consumer](https://github.com/gradual-verification/silicon-gv/blob/master/src/main/scala/rules/Consumer.scala):
```
tArgs.map(tArg => new Translator(s5.copy(g = g), v4.decider.pcs).translate(tArg) match {
  case None => sys.error("Error translating! Exiting safely.")
  case Some(expr) => expr
})
```

**Comment by jennalwise** [comment] 2022-05-23 19:54
I did some more debugging on this, and the problem is that the `regexVariableResolver` is correctly receiving an argument to resolve that is not of the type `terms.Var(identifier: Identifier, termType)`, because it is a receiver from a heap chunk. I have dealt with this in other places in the code, so I will borrow the logic from there and apply it in `regexVariableResolver`.

**Comment by jennalwise** [comment] 2022-05-24 23:22
Pushed fix to issue38 branch for testing: https://github.com/gradual-verification/silicon-gv/tree/issue38

**Comment by jennalwise** [comment] 2022-05-26 16:12
Fixed in commit https://github.com/gradual-verification/silicon-gv/commit/17bdfbf2ed43042df66e994764b56b4bbfeeb47d .

**Closed as completed by jennalwise** 2022-05-26 16:12 UTC
Labels: bug
